name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    uses: gomlang/verification/.github/workflows/ecosystem-ci.yml@185ecce1f0132ad6f0cbdf56194ee92074a869e8
    with:
      module: mail
      verification-ref: 185ecce1f0132ad6f0cbdf56194ee92074a869e8
